-- Seed data for cinema-portal-api
-- MySQL 8+
-- Run manually in MySQL client, or wire into Spring SQL init if needed.

-- =============================
-- 1) USERS
-- ============================= PASSWORD: Admin@123,Customer@123
INSERT INTO `USER` (USERNAME, PASSWORD, EMAIL, ENABLED, CREATED_DATE, LAST_UPDATED_DATE)
SELECT 'admin', '$2a$10$7QJ8c8mG8s8r2n8N5wYx9uD2xq2y5V7bN2xq2y5V7bN2xq2y5V7bO', 'admin@cinema.local', 1, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM `USER` WHERE EMAIL = 'admin@cinema.local');

INSERT INTO `USER` (USERNAME, PASSWORD, EMAIL, ENABLED, CREATED_DATE, LAST_UPDATED_DATE)
SELECT 'customer01', '$2a$10$7QJ8c8mG8s8r2n8N5wYx9uD2xq2y5V7bN2xq2y5V7bN2xq2y5V7bO', 'customer01@cinema.local', 1, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM `USER` WHERE EMAIL = 'customer01@cinema.local');

-- =============================
-- 2) CINEMA
-- =============================
INSERT INTO CINEMA (CODE, NAME, LOCATION)
SELECT 'CGV-HCM-Q1', 'CGV Vincom Center', '72 Le Thanh Ton, District 1, HCM'
WHERE NOT EXISTS (SELECT 1 FROM CINEMA WHERE CODE = 'CGV-HCM-Q1');

INSERT INTO CINEMA (CODE, NAME, LOCATION)
SELECT 'LOTTE-HCM-Q7', 'Lotte Cinema Q7', '469 Nguyen Huu Tho, District 7, HCM'
WHERE NOT EXISTS (SELECT 1 FROM CINEMA WHERE CODE = 'LOTTE-HCM-Q7');

-- =============================
-- 3) MOVIE
-- =============================
INSERT INTO MOVIE (MOVIE_CODE, TITTLE, CATEGORY, TRAILER_URL, POSTER_URL, POSTER_HORIZONTAL_URL, TIME, DESCRIPTION, RATING, LANGUAGES, DIRECTOR, CAST, ENABLE, RELEASE_DATE)
SELECT 'MV-AVATAR-2', 'Avatar: The Way of Water', 'Action, Adventure, Sci-Fi',
       'https://example.com/trailer/mv-avatar-2',
       'https://example.com/poster/mv-avatar-2.jpg',
       'https://example.com/poster/h/mv-avatar-2.jpg',
       '192 min', 'Seeded movie for development and API testing.', 'T13',
       'English, Vietnamese', 'Sample Director', 'Actor A, Actor B', 1, '2022-12-16'
WHERE NOT EXISTS (SELECT 1 FROM MOVIE WHERE MOVIE_CODE = 'MV-AVATAR-2');

INSERT INTO MOVIE (MOVIE_CODE, TITTLE, CATEGORY, TRAILER_URL, POSTER_URL, POSTER_HORIZONTAL_URL, TIME, DESCRIPTION, RATING, LANGUAGES, DIRECTOR, CAST, ENABLE, RELEASE_DATE)
SELECT 'MV-DUNE-2', 'Dune: Part Two', 'Action, Adventure',
       'https://example.com/trailer/mv-dune-2',
       'https://example.com/poster/mv-dune-2.jpg',
       'https://example.com/poster/h/mv-dune-2.jpg',
       '166 min', 'Seeded movie for development and API testing.', 'T16',
       'English, Vietnamese', 'Sample Director', 'Actor A, Actor B', 1, '2024-03-01'
WHERE NOT EXISTS (SELECT 1 FROM MOVIE WHERE MOVIE_CODE = 'MV-DUNE-2');

-- =============================
-- 4) SHOW_TIME
-- =============================
INSERT INTO SHOW_TIME (CINEMA_ID, MOVIE_ID, SCREEN_ID, PRICE, START_TIME, END_TIME, CREATED_DATE, LAST_UPDATED_DATE)
SELECT c.ID, m.ID, sc.ID, 90000,
       DATE_ADD(NOW(), INTERVAL 4 HOUR), DATE_ADD(NOW(), INTERVAL 7 HOUR), NOW(), NOW()
FROM CINEMA c
JOIN MOVIE m ON m.MOVIE_CODE = 'MV-AVATAR-2'
JOIN SCREEN sc ON sc.SCREEN_CODE = 'SC-01'
WHERE c.CODE = 'CGV-HCM-Q1'
  AND NOT EXISTS (
    SELECT 1 FROM SHOW_TIME st
    WHERE st.CINEMA_ID = c.ID
      AND st.MOVIE_ID = m.ID
      AND st.SCREEN_ID = sc.ID
  );

INSERT INTO SHOW_TIME (CINEMA_ID, MOVIE_ID, SCREEN_ID, PRICE, START_TIME, END_TIME, CREATED_DATE, LAST_UPDATED_DATE)
SELECT c.ID, m.ID, sc.ID, 120000,
       DATE_ADD(NOW(), INTERVAL 8 HOUR), DATE_ADD(NOW(), INTERVAL 11 HOUR), NOW(), NOW()
FROM CINEMA c
JOIN MOVIE m ON m.MOVIE_CODE = 'MV-DUNE-2'
JOIN SCREEN sc ON sc.SCREEN_CODE = 'SC-01'
WHERE c.CODE = 'CGV-HCM-Q1'
  AND NOT EXISTS (
    SELECT 1 FROM SHOW_TIME st
    WHERE st.CINEMA_ID = c.ID
      AND st.MOVIE_ID = m.ID
      AND st.SCREEN_ID = sc.ID
  );

INSERT INTO SHOW_TIME (CINEMA_ID, MOVIE_ID, SCREEN_ID, PRICE, START_TIME, END_TIME, CREATED_DATE, LAST_UPDATED_DATE)
SELECT c.ID, m.ID, sc.ID, 110000,
       DATE_ADD(NOW(), INTERVAL 1 DAY), DATE_ADD(DATE_ADD(NOW(), INTERVAL 1 DAY), INTERVAL 3 HOUR), NOW(), NOW()
FROM CINEMA c
JOIN MOVIE m ON m.MOVIE_CODE = 'MV-DUNE-2'
JOIN SCREEN sc ON sc.SCREEN_CODE = 'SC-02'
WHERE c.CODE = 'LOTTE-HCM-Q7'
  AND NOT EXISTS (
    SELECT 1 FROM SHOW_TIME st
    WHERE st.CINEMA_ID = c.ID
      AND st.MOVIE_ID = m.ID
      AND st.SCREEN_ID = sc.ID
  );

-- =============================
-- 5) SCREEN
-- =============================
INSERT INTO SCREEN (SCREEN_CODE, TYPE_SCREEN, NUMBER_OF_NORMAL_SEAT, NUMBER_OF_VIP_SEAT, NUMBER_OF_COUPLE_SEAT)
SELECT 'SC-01', '2D', 72, 36, 6
WHERE NOT EXISTS (SELECT 1 FROM SCREEN WHERE SCREEN_CODE = 'SC-01');

INSERT INTO SCREEN (SCREEN_CODE, TYPE_SCREEN, NUMBER_OF_NORMAL_SEAT, NUMBER_OF_VIP_SEAT, NUMBER_OF_COUPLE_SEAT)
SELECT 'SC-02', 'IMAX', 64, 24, 8
WHERE NOT EXISTS (SELECT 1 FROM SCREEN WHERE SCREEN_CODE = 'SC-02');

-- =============================
-- 6) SEAT_TYPE
-- =============================
INSERT INTO SEAT_TYPE (NAME, SURCHARGE)
SELECT 'STANDARD', 0
WHERE NOT EXISTS (SELECT 1 FROM SEAT_TYPE WHERE NAME = 'STANDARD');

INSERT INTO SEAT_TYPE (NAME, SURCHARGE)
SELECT 'VIP', 25000
WHERE NOT EXISTS (SELECT 1 FROM SEAT_TYPE WHERE NAME = 'VIP');

INSERT INTO SEAT_TYPE (NAME, SURCHARGE)
SELECT 'SWEETBOX', 40000
WHERE NOT EXISTS (SELECT 1 FROM SEAT_TYPE WHERE NAME = 'SWEETBOX');

-- =============================
-- 7) ROOM_SEATS (sample small set)
-- =============================
INSERT INTO ROOM_SEATS (SEAT_ROW, SEAT_NUMBER, SEAT_TYPE_ID, CINEMA_ID)
SELECT 'A', 1,
       (SELECT ID FROM SEAT_TYPE WHERE NAME = 'STANDARD' LIMIT 1),
       (SELECT ID FROM CINEMA WHERE CODE = 'CGV-HCM-Q1' LIMIT 1)
WHERE NOT EXISTS (
  SELECT 1 FROM ROOM_SEATS rs
  WHERE rs.SEAT_ROW = 'A' AND rs.SEAT_NUMBER = 1
    AND rs.CINEMA_ID = (SELECT ID FROM CINEMA WHERE CODE = 'CGV-HCM-Q1' LIMIT 1)
);

INSERT INTO ROOM_SEATS (SEAT_ROW, SEAT_NUMBER, SEAT_TYPE_ID, CINEMA_ID)
SELECT 'A', 2,
       (SELECT ID FROM SEAT_TYPE WHERE NAME = 'STANDARD' LIMIT 1),
       (SELECT ID FROM CINEMA WHERE CODE = 'CGV-HCM-Q1' LIMIT 1)
WHERE NOT EXISTS (
  SELECT 1 FROM ROOM_SEATS rs
  WHERE rs.SEAT_ROW = 'A' AND rs.SEAT_NUMBER = 2
    AND rs.CINEMA_ID = (SELECT ID FROM CINEMA WHERE CODE = 'CGV-HCM-Q1' LIMIT 1)
);

INSERT INTO ROOM_SEATS (SEAT_ROW, SEAT_NUMBER, SEAT_TYPE_ID, CINEMA_ID)
SELECT 'B', 1,
       (SELECT ID FROM SEAT_TYPE WHERE NAME = 'VIP' LIMIT 1),
       (SELECT ID FROM CINEMA WHERE CODE = 'CGV-HCM-Q1' LIMIT 1)
WHERE NOT EXISTS (
  SELECT 1 FROM ROOM_SEATS rs
  WHERE rs.SEAT_ROW = 'B' AND rs.SEAT_NUMBER = 1
    AND rs.CINEMA_ID = (SELECT ID FROM CINEMA WHERE CODE = 'CGV-HCM-Q1' LIMIT 1)
);

INSERT INTO ROOM_SEATS (SEAT_ROW, SEAT_NUMBER, SEAT_TYPE_ID, CINEMA_ID)
SELECT 'C', 1,
       (SELECT ID FROM SEAT_TYPE WHERE NAME = 'SWEETBOX' LIMIT 1),
       (SELECT ID FROM CINEMA WHERE CODE = 'CGV-HCM-Q1' LIMIT 1)
WHERE NOT EXISTS (
  SELECT 1 FROM ROOM_SEATS rs
  WHERE rs.SEAT_ROW = 'C' AND rs.SEAT_NUMBER = 1
    AND rs.CINEMA_ID = (SELECT ID FROM CINEMA WHERE CODE = 'CGV-HCM-Q1' LIMIT 1)
);

-- =============================
-- 8) TICKET (sample)
-- =============================
INSERT INTO TICKET (USER_ID, QR_CODE, BOOKING_NUMBER, SUBTOTAL, CREATED_DATE, LAST_UPDATED_DATE)
SELECT u.ID, 'SEED_QR_BOOK_DEMO_001', 'BOOK-DEMO-001', 270000, NOW(), NOW()
FROM `USER` u
WHERE u.EMAIL = 'customer01@cinema.local'
  AND NOT EXISTS (SELECT 1 FROM TICKET t WHERE t.BOOKING_NUMBER = 'BOOK-DEMO-001');

-- =============================
-- 9) SHOW_SEATS
-- =============================
INSERT INTO SHOW_SEATS (SHOW_TIME_ID, ROOM_SEAT_ID, IS_RESERVED, PRICE, TICKET_ID)
SELECT st.ID,
       rs.ID,
       CASE WHEN rs.SEAT_ROW = 'A' AND rs.SEAT_NUMBER IN (1, 2) THEN 1 ELSE 0 END,
       (st.PRICE + IFNULL(sty.SURCHARGE, 0)),
       CASE WHEN rs.SEAT_ROW = 'A' AND rs.SEAT_NUMBER IN (1, 2)
            THEN (SELECT t.ID FROM TICKET t WHERE t.BOOKING_NUMBER = 'BOOK-DEMO-001' LIMIT 1)
            ELSE NULL END
FROM SHOW_TIME st
JOIN CINEMA c ON c.ID = st.CINEMA_ID AND c.CODE = 'CGV-HCM-Q1'
JOIN SCREEN sc ON sc.ID = st.SCREEN_ID AND sc.SCREEN_CODE = 'SC-01'
JOIN ROOM_SEATS rs ON rs.CINEMA_ID = c.ID
LEFT JOIN SEAT_TYPE sty ON sty.ID = rs.SEAT_TYPE_ID
  AND NOT EXISTS (
    SELECT 1 FROM SHOW_SEATS ss
    WHERE ss.SHOW_TIME_ID = st.ID
      AND ss.ROOM_SEAT_ID = rs.ID
  );

